### ISSUE TITLE
Subathon timer not more then 24 Houres

### ISSUE THREAD

**Issue by Kenny2k8** [rondhi/Streamer.bot-Subathon-Countdown-Timer#2]
Hello,

the timer runs very good  but  if you set up 24 hours starttime and not maxhours on 48

The Timer will not stack the time over 24 Hours  :(

**Comment by rondhi** [comment]
Thank you for pointing this out.

I'll have into look how to solve this to format to show more than 24 hours. 

Until then, I've updated the code to include days in the timer format. You can re-import the code or:

Change line 36 from
`string countdownString = time.ToString(@"hh\:mm\:ss");`
to 
`string countdownString = time.ToString(@"d\:hh\:mm\:ss");`
will format as 0:23:59:59

Or you can go fancy (which is what I updated the code to):
`string countdownString = time.ToString(@"d' days 'hh\:mm\:ss");`
will format as `0 days 23:59:59`

**Comment by Kenny2k8** [comment]
Hi 

Thanks for the solution ;)

Would it also be possible that when the timer gets more than 24 that is counts up in hours and not in days ?

**Comment by rondhi** [comment]
Try replacing line 36 with this:
```
string countdownString = string.Format("{0}:{1}:{2}", 
            (int) time.TotalHours, 
            time.ToString("mm"), 
            time.ToString("ss"));
```

**Comment by Kenny2k8** [comment]
Nice  it works when i replace line 37 with your code

Thanks a lot
