### ISSUE TITLE
Tier 1 + 2 +3  Config Minutes

### ISSUE THREAD

**Issue by Kenny2k8** [rondhi/Streamer.bot-Subathon-Countdown-Timer#3]
Hi ,

I have found another error.  

If you set the Subathon Tier 1  or 2 or 3 Config Minutes to the value 1,5.

The counter then rounds up  to 2  minutes and if you set bits  e.g 250 then he rounded down to 1 minute

Is it possible that it does not rounded and then adds 1:30 minute?

**Comment by rondhi** [comment]
Okay I fixed it with the latest update. You can now use non-integers.
